home/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

from .views import *
app_name = 'home'
urlpatterns = [
    path('', HomeView.as_view(), name='homes'),
    path('about/', HomeView.as_view(template_name='home/about_us.html'), name='about'),
    path('logout/', logoutuser, name='logout'),
    path('search/', search, name='search'),
    path('login/', handleLogin, name='login'),
    path('create/', product_create, name='create'),
    path('add/<int:pk>/', addqty, name='add'),
    path('edit/<int:pk>/',EditProdView.as_view(), name='edit'),
    path('supedit/<int:pk>/',EditSupplierView.as_view(), name='supedit'),
    path('createsupplier/',CreateSupplierView.as_view(), name='create-supplier'),
    path('contact/',CreateContactView.as_view(), name='contact'),

    path('products/', ProductListView.as_view(), name='product-list'),
    path('delete/<int:id>/', views.delete, name='delete'),

    path('company/', CompanyListView.as_view(), name='company-list'),
    path('delete_comp/<str:id>/', views.delete_comp, name='delete_comp'),
    
    path('suppliers/', SupplierListView.as_view(), name='supplier-list'),
    path('delete_supp/<str:id>/', views.delete_supp, name='delete_supp'),

    path('sales/', SalesListView.as_view(), name='sales-list'),
    path('delete_sales/<int:id>/', views.delete_sales, name='delete_sales'),

    path('makebill/', views.makebill, name='makebill'),
    path('dashboard/', views.dashboard, name='dashboard'),
    # path('create/', ProductCreate.as_view(), name='create'),
    path('createemployee/', views.CreateEmployeeView, name='create-employee'),
    path('createpatient/', views.CreatePatientView, name='create-patient'),

    path('empedit/<int:pk>/',EditEmployeeView.as_view(), name='empedit'),
    path('delete_emp/<int:pk>/', views.delete_emp, name='delete_emp'),

    path('patedit/<int:pk>/',EditPatientView.as_view(), name='patedit'),
    path('delete_patient/<str:id>/', views.delete_pat, name='delete_pat'),

    path('employee/', views.employees, name='employee-list'),
    path('patient/', views.patients, name='patient-list'),
    path('invoice/', views.invoice, name='invoice'),

    path('supplier_invoice/', views.supplier_invoice, name='supplier-invoice'),
    path('delete_supp_inv/<str:id>/', views.delete_supp_inv, name='delete_supp_inv'),

    path('add_supplier_invoice/', views.add_supplier_invoice, name='add-supplier-invoice'),
]

medicalStore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/forms.py
from django import forms
from .fields import ListTextWidget
from .models import Company, Product, Sales, Supplier,Contact, Patient, Employee, SupplierInvoice
from django.forms import ModelForm, DateInput


class FormsetForm(forms.Form):
    delete = forms.BooleanField(required=False, initial=False)
    # some other fields with data

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ('name',)

class QtyForm(forms.Form):
    value = forms.IntegerField()

class BillForm(ModelForm):
    name = forms.CharField(required=True,widget=forms.TextInput(attrs={'class':'form-control' , 'autocomplete': 'off','pattern':'[A-Za-z ]+', 'title':'Enter Characters Only'}))
    class Meta:
        model = Product
        fields=('name',)

    def __init__(self, *args, **kwargs):
      _company_list = kwargs.pop('data_list', None)
      super(BillForm, self).__init__(*args, **kwargs)
      self.fields['name'].widget = ListTextWidget(
          data_list=_company_list, name='name-list')

class FormForm(ModelForm):
    company = forms.CharField(required=True)
    mfg = forms.DateField(widget=forms.TextInput(attrs={'type': 'date', 'class': 'form-control'}))
    exp = forms.DateField(widget=forms.TextInput(attrs={'type': 'date', 'class': 'form-control'}))
    class Meta:
        model = Product
        fields= '__all__'

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'autocomplete': 'off','pattern':'[A-Za-z ]+', 'title':'Enter Characters Only'}),
            'batch_no': forms.TextInput(attrs={'class': 'form-control', 'autocomplete': 'off','pattern':'[0-9]+', 'title':'Enter Numbers Only'}),
        }
          
    def __init__(self, *args, **kwargs):
      _company_list = kwargs.pop('data_list', None)
      super(FormForm, self).__init__(*args, **kwargs)
      self.fields['company'].widget = ListTextWidget(data_list=_company_list, name='company-list')

class ProductForm(ModelForm):
    mfg = forms.DateField(widget=forms.TextInput(attrs={'type': 'date', }))
    exp = forms.DateField(widget=forms.TextInput(attrs={'type': 'date', }))
    class Meta:
        model = Product
        fields= ('mfg','exp','cost','selling_price','qty','supplier')


class SupplierForm(ModelForm):
    class Meta:
        model = Supplier
        fields= '__all__'

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'autocomplete': 'off','pattern':'[A-Za-z ]+', 'title':'Enter Characters Only'}),
            'phone': forms.TextInput(attrs={'class': 'form-control', 'autocomplete': 'off','pattern':'[0-9]+', 'title':'Enter Numbers Only'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'})
        }

class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields= '__all__'

class EmployeeForm(ModelForm):
    class Meta:
        model = Employee
        fields= '__all__'

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'autocomplete': 'off','pattern':'[A-Za-z ]+', 'title':'Enter Characters Only'}),
            'phone': forms.TextInput(attrs={'class': 'form-control', 'autocomplete': 'off','pattern':'[0-9]+', 'title':'Enter Numbers Only'})
        }


class PatientForm(ModelForm):
    class Meta:
        model = Patient
        fields= '__all__'

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'autocomplete': 'off','pattern':'[A-Za-z ]+', 'title':'Enter Characters Only'}),
            'phone': forms.TextInput(attrs={'class': 'form-control', 'autocomplete': 'off','pattern':'[0-9]+', 'title':'Enter Numbers Only'}),
            'gender': forms.TextInput(attrs={'class': 'form-control', 'autocomplete': 'off', 'pattern':'[A-Za-z ]+', 'title':'Enter Characters Only'}),
            'doctor_name': forms.TextInput(attrs={'class': 'form-control', 'autocomplete': 'off', 'pattern':'[A-Za-z ]+', 'title':'Enter Characters Only'})
        }

class SupplierInvoiceForm(ModelForm):
    order_date = forms.DateField(widget=forms.TextInput(attrs={'type': 'date', }))
    delivery_date = forms.DateField(widget=forms.TextInput(attrs={'type': 'date', }))
    class Meta:
        model = SupplierInvoice
        fields = '__all__'

        widgets = {
            'invoice_number': forms.TextInput(attrs={'class': 'form-control', 'autocomplete': 'off','pattern':'[0-9]+', 'title':'Enter Numbers Only'}),
            'amount': forms.TextInput(attrs={'class': 'form-control', 'autocomplete': 'off','pattern':'[0-9]+', 'title':'Enter Numbers Only'}),
        }

home/views.py
import json
import random
from django.shortcuts import render
from django.template import RequestContext
from django.template import loader
from django.forms import formset_factory
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash, get_user_model
from django.contrib.auth.models import User
from django.contrib.auth.views import PasswordChangeForm, PasswordResetCompleteView, \
    PasswordResetConfirmView, PasswordResetView, PasswordResetForm, PasswordResetDoneView
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseRedirect
from django.views.generic import View, TemplateView
import time
from math import ceil
from django.views import generic, View
from django.views.generic.base import RedirectView
from django.urls import reverse_lazy
from .models import Company, Product, Sales, Supplier,Contact, Employee, Patient
from .forms import *
from django.db.models import Q
from django.contrib import messages

from django.core.exceptions import ObjectDoesNotExist



def search(request):
    query = request.POST.get('q', '')
    if query:
        queryset = (Q(name__icontains=query)) | (Q(company__icontains=query)) | (Q(batch_no__icontains=query))
        products = Product.objects.filter(queryset).distinct()
    else:
       products = []
    
    return render(request, "home/product_list.html", {'products': products})

class HomeView(TemplateView):
    template_name = "home/home.html"


def logoutuser(request):
    logout(request)
    messages.success(request, "Successfully logged out!")
    return redirect('home:homes')


def handleLogin(request):
    if request.method == 'POST':
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}")
                return redirect('home:homes')
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()
    return render(request=request,
                  template_name="home/login.html",
                  context={"form": form})


def product_create(request):
    if request.method == "POST":
        form = FormForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            company = form.cleaned_data['company']
            subcheck = Company.objects.filter(name=company)
            if not subcheck:
                Company.objects.create(name=company)
            subchecks = Product.objects.filter(name=name)
            if subchecks:
                messages.error(
                    request, 'Alreay this product has included to the list.!')
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
            form.save()
            messages.success(request, 'Successfully added to the list.!')
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        company_list = Company.objects.all()
        form = FormForm(data_list=company_list)
    return render(request, 'home/product.html', {'form': form})


class ProductListView(generic.ListView):
    model = Product
    template_name = 'home/product_list.html'
    context_object_name = 'products'
    queryset = Product.objects.all().order_by('name')
class CompanyListView(generic.ListView):
    model = Company
    template_name = 'home/company_list.html'
    context_object_name = 'company'
    queryset = Company.objects.all().order_by('name')
class SupplierListView(generic.ListView):
    model = Supplier
    template_name = 'home/supplier_list.html'
    context_object_name = 'supplier'
    queryset = Supplier.objects.all().order_by('name')
class SalesListView(generic.ListView):
    model = Sales
    template_name = 'home/sales_list.html'
    context_object_name = 'sales'
    queryset = Sales.objects.all().order_by('name')
class EmployeeListView(generic.ListView):
    model = Employee
    template_name='home/employee_list.html'
    context_object_name='employee'
    queryset= Sales.objects.all().order_by('name')
class PatientListView(generic.ListView):
    model = Employee
    template_name='home/patient_list.html'
    context_object_name='patient'
    queryset= Sales.objects.all().order_by('name')
def delete(request,id):
    prod=Product.objects.get(id=id)
    prod.delete()
    return redirect('/products')

# function for delete Company 
def delete_comp(request, id):
    if request.method == 'POST':
        pi = Company.objects.get(id=id)
        pi.delete()
        return redirect('/company') 

# function for delete Sales 
def delete_sales(request, id):
    if request.method == 'POST':
        pi = Sales.objects.get(id=id)
        pi.delete()
        return redirect('/sales')        


def employees(request):
    employees = Employee.get_all_employees()
    return render(request, 'home/employee_list.html', {'employees': employees})

def patients(request):
    patients = Patient.get_all_patients()
    return render(request, 'home/patient_list.html', {'patients': patients})    

def addqty(request, pk):
    if request.method == "POST":
        qty=request.POST.get('qty')
        p = Product.objects.get(id=pk)
        p.qty = p.qty + int(qty)
        p.save()
    return redirect('home:product-list')

def makebill(request):
    if request.method == "POST":
        cart = request.POST.get('cart')
        price = request.POST.get('price')
        n = request.POST.get('name')
        phone = request.POST.get('phone')
        data = json.loads(cart)
        for c in data:
            name = c['name']
            qty = c['qty']
            prod = Product.objects.get(name=name)
            prod.qty = prod.qty - int(qty)
            if prod.qty <= 0:
                messages.warning(request, f'{prod.name} has finished')
                prod.delete()
            else:
                prod.save()
        p = Sales(items_json=cart, amount=price, name=n, phone=phone)
        p.save()
        return redirect('home:invoice')
        total = price
    else:
        product = Product.objects.all().order_by('name')
        product_list = list(product.values('name', 'cost'))
        context = {}
        context["product"] = json.dumps(product_list)
        try:
            context["total"] = total
        except:
            pass
        return render(request, 'makebill.html', context)
        

def invoice(request):
    return render(request, 'home/invoice.html')

        
from .forms import ProductForm
class EditProdView(generic.UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'home/product.html'
    def get_success_url(self):
        id = self.kwargs['pk']
        return reverse_lazy('home:product-list')
class EditSupplierView(generic.UpdateView):
    model = Supplier
    form_class = SupplierForm
    template_name = 'home/addsupplier.html'
    def get_success_url(self):
        id = self.kwargs['pk']
        return reverse_lazy('home:supplier-list')
class EditEmployeeView(generic.UpdateView):
    model = Employee
    form_class = EmployeeForm
    template_name = 'home/addemployee.html'
    def get_success_url(self):
        id = self.kwargs['pk']
        return reverse_lazy('home:employee-list')
class EditPatientView(generic.UpdateView):
    model = Patient
    form_class = PatientForm
    template_name = 'home/addpatient.html'
    def get_success_url(self):
        id = self.kwargs['pk']
        return reverse_lazy('home:patient-list')
class CreateSupplierView(generic.CreateView):
    model = Supplier
    form_class = SupplierForm
    template_name = 'home/addsupplier.html'
    def get_success_url(self):
        return reverse_lazy('home:supplier-list')

# function for delete Suppliers
def delete_supp(request, id):
    if request.method == 'POST':
        pi = Supplier.objects.get(id=id)
        pi.delete()
        return redirect('/suppliers')        
# class CreateEmployeeView(generic.CreateView):
#     model = Employee
#     form_class = EmployeeForm
#     template_name = 'home/addemployee.html'
#     def get_success_url(self):
#         return reverse_lazy('home:employee-list')
# class CreatePatientView(generic.CreateView):
#     model = Patient
#     form_class = PatientForm
#     template_name = 'home/addpatient.html'
#     def get_success_url(self):
#         return reverse_lazy('home:patient-list')
class CreateContactView(generic.CreateView):
    model = Contact
    form_class = ContactForm
    template_name = 'home/contact_us.html'
    def get_success_url(self):
        return reverse_lazy('home:product-list')


def CreateEmployeeView(request):
    form = EmployeeForm
    if request.method == 'POST':
        form = EmployeeForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Employee added Successfully!')
            return redirect('/createemployee')
    else:
        form = EmployeeForm
    return render(request, 'home/addemployee.html', {'form': form})

# function for delete Employee 
def delete_emp(request, pk):
   if request.method == 'POST':
      try:       
         pi = Employee.objects.get(id=pk)
         pi.delete()
      except ObjectDoesNotExist:
         print(f"Record is not found with the id: {pk}")
      return redirect('/employee')

def CreatePatientView(request):

templates/home/about_us.html
{% extends 'basic.html' %}

{% block title%} About {% endblock %}
{% block aboutactive %} active{% endblock aboutactive %}
{% block body %}

<div class="col-md-6 offset-md-3">

            <h1 class="bd-title" id="content">About</h1>
            <p class="bd-lead">This project is made for Pharmacy Database Management System. </p>

           <h1>Team members : </h1>
            <p>Sivanand Mahapatra </p>
            <p>Arpit Arora</P>
            </p>Nitish Kumar</p>
            <p>Athrey Agnihotri</p>
            
            <h1>Technology :</h1>
            <h4>Backend:</h4> <P>Python Django-Framework.</P>
            <h4>Frontend:</h4><p> HTML5, CSS, Javascript.</P>

            <br>
            <br>
            
             <h2>
                <center>DESIGNED BY STUDENTS OF KLE TECHNOLOGICAL UNIVERSITY!</center>
            </h2>
       



            


</div>
<body style="
      width: 100%;
    height: 100vh;
    background: linear-gradient(rgba(0, 0, 0, 0.2), rgba(0, 0, 0, 0.2)), url('/static/images/bg2.jpg');
    background-size: cover; 
    font-family: 'Roboto', sans-serif;
      
    ">
{% endblock %}
{% block css %}
p{
text-align:justify;
line-height:25px;
{% comment %} text-shadow: 1px 2px blue; {% endcomment %}
text-indent:30px;
padding-left:30px;
text-transformation: capitalize;
}
p a{
    color:blue;
}
a:hover{
    border-bottom:2px solid red;
}
{% endblock css %}

templates/home/add_supplier_invoice.html
{% extends 'basic.html' %}
{% block body %}
{% load static %}
{% load crispy_forms_tags %}
{% if user.is_authenticated %}
<div class="col-md-6 offset-md-3">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group mx-auto">
                <legend class="border-bottom text-center mb-4"><h2> Supplier Invoice </h2></legend>
                {{ form|crispy }}
            </fieldset>
            <button class="btn btn-outline-info " type="submit" value="submit">Save</button>
        </form>
</div>
<!-- background:
        url('/static/images/map1.jpg');
      background-size: 1500px 805px; -->


<body style="
      width: 100%;
    height: 100vh;
    background: linear-gradient(rgba(0, 0, 0, 0.2), rgba(0, 0, 0, 0.2)), url('/static/images/bg2.jpg');
    background-size: cover;
    font-family: 'Roboto', sans-serif;
      
    ">
{% else %}
<h2>Please Log in to Create a Post</h2>
{% endif %}
{% endblock body %}

templates/home/addemployee.html
{% extends 'basic.html' %}
{% block body %}
{% load static %}
{% load crispy_forms_tags %}
{% if user.is_authenticated %}
<div class="col-md-6 offset-md-3">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group mx-auto">
                <legend class="border-bottom text-center mb-4"><h2>Employee</h2></legend>
                {{ form|crispy }}
            </fieldset>
            <button class="btn btn-outline-info " type="submit" value="submit">Save</button>
        </form>
</div>
    <!-- background:
        url('/static/images/map1.jpg');
      background-size: 1500px 805px; -->

<body style="
      width: 100%;
    height: 100vh;
    background: linear-gradient(rgba(0, 0, 0, 0.2), rgba(0, 0, 0, 0.2)), url('/static/images/bg2.jpg');
    background-size: cover;
    font-family: 'Roboto', sans-serif;
    ">
{% else %}
<h2>Please Log in to Create a Post</h2>
{% endif %}
{% endblock body %}

templates/home/company_list.html
{% extends 'basic.html' %}
{% block body %}
{% load static %}
{% load crispy_forms_tags %}
{% if user.is_authenticated %}
<div class="col-md-6 offset-md-3">
 <h3 class="text-center">List Of Companies</h3>
<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Company ID</th>
      <th scope="col">Company Name</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
  {% for p in company %}
    <tr>
      <th scope="row">{{p.id}}</th>
      <td>{{p.name}}</td>
      <td>
        <form action="{% url 'home:delete_comp' p.id %}" method="post">
          {% csrf_token %}
          <input type="submit" class="btn btn-primary btn-sm" value="Delete">
        </form>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
</div>

<!-- background:
        url('/static/images/map1.jpg');
      background-size: 1500px 805px; -->
<body style="
      width: 100%;
    height: 100vh;
    background: linear-gradient(rgba(0, 0, 0, 0.2), rgba(0, 0, 0, 0.2)), url('/static/images/bg2.jpg');
    background-size: cover; 
    font-family: 'Roboto', sans-serif;
      
    ">
{% else %}
<h2>Please Log in to Create a Post</h2>
{% endif %}
{% endblock body %}

templates/home/employee_list.html
{% extends 'basic.html' %}
{% block body %}
{% load static %}
{% load crispy_forms_tags %}
{% if user.is_authenticated %}
<div class="col-md-7 offset-md-2">
 <h3 class="text-center">List Of Employees</h3>
<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Employee Name</th>
      <th scope="col">Years of Experience</th>
      <th scope="col">Phone</th>
      <th scope="col">Salary</th>
      <th scope="col">Edit</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
  {% for employee in employees %}
    <tr>
      <th scope="row">{{employee.id}}</th>
      <td>{{employee.name}}</td>
      <td>{{employee.years_of_exp}}</td>
      <td>{{employee.phone}}</td>
      <td>{{employee.salary}}</td>
      <td><a href="/empedit/{{employee.id}}/"><button class="btn btn-primary btn-sm">Edit</button></a></td>
      <td>
        <form action="{% url 'home:delete_emp' employee.id %}" method="post">
          {% csrf_token %}
          <input type="submit" class="btn btn-primary btn-sm" value="Delete">
        </form>
      </td>  
        {# <a href="#"><button class="btn btn-primary btn-sm">Delete</button></a></td> #}
    </tr>
    {% endfor %}
  </tbody>
</table>
</div>



<!-- background:
        url('/static/images/map1.jpg');
      background-size: 1500px 805px; -->
<body style="
      width: 100%;
    height: 100vh;
    background: linear-gradient(rgba(0, 0, 0, 0.2), rgba(0, 0, 0, 0.2)), url('/static/images/bg2.jpg');
    background-size: cover; 
    font-family: 'Roboto', sans-serif;
      
    ">
{% else %}
<h2>Please Log in to Create a Post</h2>
{% endif %}
{% endblock body %}

templates/home/product_list.html
{% extends 'basic.html' %}
{% block body %}
{% load static %}
{% load crispy_forms_tags %}
{% if user.is_authenticated %}
<div class="container-fluid">
<div class="col-md-9 ">
<h3 class="text-center">List Of Medicines</h3>
<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Medicine ID</th>
      <th scope="col">Medicine Name</th>
      <th scope="col">Power (in mg)</th>
      <th scope="col">Company Name</th>
      <th scope="col">Cost Price</th>
      <th scope="col">Selling Price</th>
      <th scope="col">MFG Date</th>
      <th scope="col">EXP Date</th>
      <th scope="col">Quantity</th>
      <th scope="col">Supplier Name</th>
      <th scope="col">ADD</th>
      <th scope="col">DELETE</th>
      <th scope="col">Edit</th>
    </tr>
  </thead>
  <tbody>
  {% for p in products %}
    <tr>
      <th scope="row">{{p.id}}</th>
      <td>{{p.name}}</td>
      <td>{{p.batch_no}}</td>
      <td>{{p.company}}</td>
      <td>{{p.cost}} RS/ps</td>
      <td>{{p.selling_price}} RS/ps</td>
      <td>{{p.mfg}}</td>
      <td>{{p.exp}}</td>
      <td>{{p.qty}}</td>
      <td>{{p.supplier}}</td>
      <td> <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal1">
  ADD Quantitiy
</button></td>
      <td><button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  Delete
</button></td>
      <td><button class="btn btn-primary text-white"> <a href="/edit/{{p.id}}/">Edit</a></button></td>


<!-- Modal -->
<div class="modal fade"  id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog  modal-dialog-centered">
    <div class="modal-content" style="background: none; border: 2px solid green;">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">DELETE</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" >
       Are You Sure to delete {{p.name}}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary"><a href="{% url 'home:delete' p.id %}">Delete</a></button>
      </div>
    </div>
  </div>
</div>
<!-- Modal -->
<div class="modal fade"  id="exampleModal1" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog  modal-dialog-centered">
    <div class="modal-content" style="background:none; border: 2px solid green;">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">ADD Available Quantitiy</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" >
       <form method="post" action="/add/{{p.id}}/" enctype="multipart/form-data" >
            {% csrf_token %}
            <fieldset class="form-group mx-auto">
                <legend class="border-bottom text-center mb-4"><h2>Add Quantitiy in {{p.name}}</h2></legend>
                <input type="text" name="qty">
            </fieldset>
            <button class="btn btn-outline-info " type="submit" value="submit">Add</button>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
      {% comment %} <td><a href="{% url 'home:delete' pk=p.id %}">Delete</a></td> {% endcomment %}
    </tr>
    {% endfor %}
  </tbody>
</table>
</div>
</div>

<!-- background:
        url('/static/images/map1.jpg');
      background-size: 1500px 805px; -->


<body style="
      width: 100%;
    height: 100vh;
    background: linear-gradient(rgba(0, 0, 0, 0.2), rgba(0, 0, 0, 0.2)), url('/static/images/bg2.jpg');
    background-size: cover; 
    font-family: 'Roboto', sans-serif;
      
    ">
{% else %}
<h2>Please Log in to Create a Post</h2>
{% endif %}
{% endblock %}
{% block css %}

{% endblock  %}