home/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

from .views import *
app_name = 'home'
urlpatterns = [
    path('', HomeView.as_view(), name='homes'),
    path('about/', HomeView.as_view(template_name='home/about_us.html'), name='about'),
    path('logout/', logoutuser, name='logout'),
    path('search/', search, name='search'),
    path('login/', handleLogin, name='login'),
    path('create/', product_create, name='create'),
    path('add/<int:pk>/', addqty, name='add'),
    path('edit/<int:pk>/',EditProdView.as_view(), name='edit'),
    path('supedit/<int:pk>/',EditSupplierView.as_view(), name='supedit'),
    path('createsupplier/',CreateSupplierView.as_view(), name='create-supplier'),
    path('contact/',CreateContactView.as_view(), name='contact'),

    path('products/', ProductListView.as_view(), name='product-list'),
    path('delete/<int:id>/', views.delete, name='delete'),

    path('company/', CompanyListView.as_view(), name='company-list'),
    path('delete_comp/<str:id>/', views.delete_comp, name='delete_comp'),
    
    path('suppliers/', SupplierListView.as_view(), name='supplier-list'),
    path('delete_supp/<str:id>/', views.delete_supp, name='delete_supp'),

    path('sales/', SalesListView.as_view(), name='sales-list'),
    path('delete_sales/<int:id>/', views.delete_sales, name='delete_sales'),

    path('makebill/', views.makebill, name='makebill'),
    path('dashboard/', views.dashboard, name='dashboard'),
    # path('create/', ProductCreate.as_view(), name='create'),
    path('createemployee/', views.CreateEmployeeView, name='create-employee'),
    path('createpatient/', views.CreatePatientView, name='create-patient'),

    path('empedit/<int:pk>/',EditEmployeeView.as_view(), name='empedit'),
    path('delete_emp/<int:pk>/', views.delete_emp, name='delete_emp'),

    path('patedit/<int:pk>/',EditPatientView.as_view(), name='patedit'),
    path('delete_patient/<str:id>/', views.delete_pat, name='delete_pat'),

    path('employee/', views.employees, name='employee-list'),
    path('patient/', views.patients, name='patient-list'),
    path('invoice/', views.invoice, name='invoice'),

    path('supplier_invoice/', views.supplier_invoice, name='supplier-invoice'),
    path('delete_supp_inv/<str:id>/', views.delete_supp_inv, name='delete_supp_inv'),

    path('add_supplier_invoice/', views.add_supplier_invoice, name='add-supplier-invoice'),
]

medicalStore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/basic.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
        integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous" />
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>

    <title>{% block title%} Shilpa Medical Store {% endblock %}</title>
    {% load static %}
    <script src="{% static 'notifications/notify.js' %}" type="text/javascript"></script>
    <link href="{% static 'css/style.css'  %}" rel="stylesheet" />

    <style>
        {
            % block css %
        }

        {
            % endblock css %
        }

    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@200&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Oswald&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap');

    </style>
</head>


    
    <h1 class="text-center" style="color: grey; font-family: 'Oswald', sans-serif;"> PHARMACY DATABASE MANAGEMENT SYSTEM</h1>
    <nav class="navbar navbar-expand-lg navbar-light" style="background: none; color: grey; text-color: grey; font-family: 'Poppins', sans-serif;">
        {% comment %} <a class="navbar-brand" style="color: grey; text-color: grey" href="/profile/">DesireBD</a>
        {% endcomment %}
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon" style="color: grey; text-color: grey">Menu</span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="nav justify-content-center">
                <li class="nav-item {% block blogactive %} {% endblock blogactive %}">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/dashboard/">Dashboard</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        View
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown"
                        style="text-color: #26f1fb">
                        <a class="dropdown-item" style="color: grey" href="/products/">Medicines</a>
                        <a class="dropdown-item" style="color: grey" href="/sales/">Sales List</a>
                        <a class="dropdown-item" style="color: grey" href="/company/">Companies</a>
                        <a class="dropdown-item" style="color: grey" href="/suppliers/">Supplier List</a>
                        <a class="dropdown-item" style="color: grey" href="/employee/">Employees</a>
                        <a class="dropdown-item" style="color: grey" href="/patient/">Patient List</a>
                        <a class="dropdown-item" style="color: grey" href="/supplier_invoice/"> Supplier Invoice </a>
                    </div>
                </li>
                
                
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        ADD
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="color: grey">
                        <a class="dropdown-item" style="color: grey" href="/create/">Medicine</a>
                        <a class="dropdown-item" style="color: grey" href="/makebill/">Bill</a>
                        <a class="dropdown-item" style="color: grey" href="/createsupplier/">Supplier</a>
                        <a class="dropdown-item" style="color: grey" href="/createemployee/">Employee</a>
                        <a class="dropdown-item" style="color: grey" href="/createpatient/">Patient</a>
                        <a class="dropdown-item" style="color: grey" href="/add_supplier_invoice/"> Supplier Invoice </a>
                    </div>
                </li>
               
                {% comment %} <li class="nav-item {% block contactactive %} {% endblock contactactive %}">
                    <a class="nav-link" href="/contact/">Contact</a>
                </li> {% endcomment %}

                <li class="nav-item {% block aboutactive %} {% endblock aboutactive %}">
                    <a class="nav-link" href="/about/">About</a>
                </li>

                 
               
   
   

                {% comment %} <div>{% now "SHORT_DATETIME_FORMAT" %}</div> {% endcomment %}

                {% if user.is_authenticated %}
                <ul class="navbar-nav">
                    <form method="post" action="/search/" class="form-inline my-2 my-lg-0">
                        {% csrf_token %}
                        <li>
                            <input class="form-control mr-sm-2" style="color: #26f1fb" type="search"
                                placeholder="Search" aria-label="Search" name="q" id="q" />
                        </li>
                        
                    </form>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{request.user}}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown"
                            style="color: grey">
                            
                            <a class="dropdown-item" style="color: grey" href="{% url 'home:logout' %}">Logout</a>
                        </div>
                    </li>
                </ul>
                {% else %}

                <li class="nav-item {% block login %} {% endblock login %}">
                    <a class="nav-link" href="{% url 'home:login' %}">Login</a>
                </li>

                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="">{% now "h:i A" as current_time %} {{ current_time|center:"150" }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="">{% now "D jS F Y" %}</a>
                </li>
            </ul>
        </div>
    </nav>

    {% for message in messages %}

    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        <strong></strong> {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <body style="
      width: 100%;
    height: 100vh;
    background: linear-gradient(rgba(0, 0, 0, 0.2), rgba(0, 0, 0, 0.2)), url('/static/images/bg2.jpg');
    background-size: cover;
    font-family: 'Roboto', sans-serif;
     
    ">
    {% endfor %}
    <br />
    {% block body %} {% endblock %} {% block js %} {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.js"
        integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
        integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
        integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
        crossorigin="anonymous"></script>
</body>

</html>

templates/basicc.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
{% load static %}
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
    integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
  <script src="{% static 'notifications/notify.js' %}" type="text/javascript"></script>
  <title>{% block title %} {% endblock %}</title>
  <link  rel='stylesheet' href="/static/bang/style.css">
</head>

<body style="background:  linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.6)),url('/static/images/ban1.jpg');
background-size: cover;
      background-attachment: fixed;
      background-position: top;">
<div class="menu-bar">
        <ul>
            <li><a href="/"><i class="fa fa-home"></i> Home</a></li>
            <li><a href=""><i class="fa fa-user"></i>View</a>
                <div class="sub-menu-1">
                    <ul>
                        <li><a href="/products/">Products</a></li>
                        <li><a href="/tolet/viewtolet/">To-let Posts</a></li>
                        <li><a href="/profile/addsubject/">Subjects List</a></li>
                        <li><a href="/profile/userlist/">Users List</a></li>
                    </ul>
                </div>
            </li>
            <li><a href=""><i class="fa fa-users"></i>Create</a>
                <div class="sub-menu-1">
                    <ul>
                        <li><a href="/create/">Stock</a></li>
                        <li><a href="/tolet/posttolet/">To-let Posts</a></li>
                    </ul>
                </div>
            </li>
            {% comment %} <li>          <a href="/profile/contact/">Contact</a>    </li>
        <li>          <a href="/profile/about_us/">About</a>        </li> {% endcomment %}
        {% if user.is_authenticated %}
            <li><a href=""><i class="fa fa-users"></i>{{request.user}}</a>
                <div class="sub-menu-1">
                    <ul>
                        <li><a href="/profile/userprofile/">Profile</a></li>
                        <li><a href="/profile/notification/">Notifications</a></li>
                        <li><a href="{% url 'home:logout' %}">Logout</a></li>
                    </ul>
                </div>
            </li>
        <form method="GET" action="/posts/search/" class="form-inline my-2 my-lg-0">
          {% csrf_token %}
          <li>
          <input class="in " type="search" placeholder="Search" aria-label="Search" name="q" id="search"></li>
          <li><button class="btn  btn-sm" type="submit" value="{{ query|escape }}">Search</button></li>
        </form>
        <li>
        <a href="">{% now "h:i A" as current_time %}
    {{ current_time|center:"150"  }} {% now "D, F jS, Y" %}
        </a>
        </li>
        </ul>
    </div>
        
      </ul>
      {% else %}

      <li class=" {% block SignUp %}
      {% endblock SignUp %} ">
        {% comment %} <a href="{% url 'signup' %}">SignUp</a> {% endcomment %}
      </li>
      <li class=" {% block Login %}
      {% endblock Login %} ">
        <a href="{% url 'home:login' %}">Login</a>
      </li></ul>
      {% endif %}
      

    </div>
      
  </nav>
 
</div>
<body style="
      background:
        url('/static/images/map4.jpg');
      background-size: 1500px 805px;
      
    ">
  
  {% for message in messages  %}
  <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
    <strong></strong> {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% endfor %}
  <br>
  {% block body %} {% endblock %}
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
    integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
    integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
    crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
			  ></script>
  <script>
  {% block js %} {% endblock %}
  
  </script>
</body>

</html>

templates/list.html
{% extends 'basic.html' %} {% block body %}{% if items_json %}
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<script type="text/javascript">
  var people = {{ items_json|safe }};
</script>
<div id="app">
  [[message]]
  <ul>
    <li v-for="person in people">
      <a v-bind:href="person.url">[[ person.name ]]</a>
      <button v-on:click="greet(person.name)">hey</button>
    </li>
  </ul>
</div>
<body style="
      background:
        url('/static/images/map1.jpg');
      background-size: 1500px 805px;
      
    ">
<script>
  var app = new Vue({
    delimiters: ["[[", "]]"],
    el: "#app",
    data: {
      message: "Hello Vue!",
      people: people,
    },
    methods: {
      greet: function (name) {
        console.log("Hello from " + name + "!");
      },
    },
  });
</script>
{% else %}
<p>No items available.</p>
{% endif %} {% endblock %}

templates/makebill.html
{% extends 'basic.html' %} {% block body %}{% if product %}
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<script type="text/javascript">
    var product = {{ product| safe }};
</script>

<div id="app">
    {% comment %} [[message]] {% endcomment %}
    <div class="container">
    {% if total %}
    <h3 class="text-center">Your Bill is Done. </h3>
    <h3 class="text-center">Your Total= {{total}}rs </h3>
    <h5 class="text-center">Make Another bill from below</h5>
 
    {% endif %}


        <div class="row">
            <div class="col-sm-6">
                <h3 class="text-center">Make a Bill</h3>
               
                <div class="input-group mb-3">

                    <div class="input-group-prepend">
                        <label class="input-group-text" for="inputGroupSelect01">Products</label>
                    </div>
                    <select name="LeaveType" v-model="key" class="custom-select" id="inputGroupSelect01" @change="addToCart($event)">
                        <option></option>
                        <option v-for="(person,index) in product" :key="index" 
                            :value="person">[[person.name]]

                        </option>
                    </select>
                
                </div>
            {% comment %} <ul>
                <li v-for="(p,index) in product" :key="index">[[p.name]]- [[p.cost]]tk <button @click="addToCart(p)">Add TO cart</button></li>
            </ul> {% endcomment %}

                
            </div>



            <div class="col-sm-6">
                <h3 class="text-center">Your Billing Cart</h3>

                <ul class="list-group">
                    <li class="list-group-item" style="color: #000000; background: #fff;">
                        <span class="item-name">Name</span> - - - - - - - - - - - - - - - - - - - -        
                        <span class="item-qty text-center" text-align="center">Quantity</span> - - - - - - - - - - - - - - - - - - - - - -
                        <span class="item-price float-right">Price</span>
                    </li>
                    
                    <li v-for="(item, index) in cart" :key="index" class="list-group-item" style="color: #000000; background: #fff;">
                        <span class="float-right">
                            <button @click="removeItem" class="btn btn-sm btn-danger" style="width: 20px; border-color: #000000; color: #000000;">
                                -
                            </button>   
                        </span>
                        <span class="item-name">[[item.name]]</span>
                        <span class="item-price float-right">$[[item.cost]] </span>
                       <span class="float-right"> <input  style="color:black; background:white;" placeholder="Quantity?" type="text" v-model="item.qty" /> </span>
                    </li>
                    <hr />

                    <li class="list-group-item" style="color: #000000; background: #fff;">
                        <span class="item-name">Total</span>
                        <span class="item-price float-right" >Rs. [[totalPrice]] </span>
                    </li  class="list-group-item">

                    <form action="/makebill/" method="post">
                        {% csrf_token %}
                        <input type="hidden" :value="totalPrice" name="price" >
                        <input type="hidden" :value="cartReturn" name="cart" >
                        <div class="form-group">
                          <label for="name">Name: </label>
                          <input type="text" class="form-control" name="name"
                            placeholder="Enter Customer Name" >
                        </div>
                        <div class="form-group">
                          <label for="phone">Phone:</label>
                          <input type="text" class="form-control"  name="phone"
                            placeholder="Enter Customer Phn Number">  
                        </div>

                            <h2> GST = [[gST]] </h2>
                            <h2> Discount = [[diSCOUNT]] </h2>
                            <h2> Net Price = [[net_Price]] </h2>

                        
                        <button class="btn btn-sm btn-primary" type="submit">Make Bill</button>
                    </form>
                    
                    <hr />
                </ul>
            </div>
        </div>
    </div>
</div>
<script>
var app = new Vue({
  delimiters: ["[[", "]]"],
  el: "#app",
  data: {
    message: "Hello Vue!",
    product: product,
    items: [],
    cart: [],
    key: "",
    qty: 0,
  },
  computed: {
    totalPrice() {
      var total = 0.0;
      this.cart.forEach((item) => {
        total += parseFloat(item.cost * item.qty);
      });
      return total;
    },
    gST(){
      var total = 0.0;
      this.cart.forEach((item) => {
        total += parseFloat(item.cost * item.qty);
      });
      return total*0.05;
    },
    diSCOUNT(){
      var total = 0.0;
      this.cart.forEach((item) => {
        total += parseFloat(item.cost * item.qty);
      });
      return total*0.1;
    },
    net_Price(){
      var total = 0.0;
      this.cart.forEach((item) => {
        total += parseFloat(item.cost * item.qty);
      });
      return total*0.95;
    },
    cartReturn() {
      return JSON.stringify(this.cart);
    },
  },
  methods: {
    removeItem(index) {
      this.cart.splice(index, 1);
    },
    addToCart(event) {
      this.cart.push({
        name: this.key.name,
        cost: this.key.cost,
        qty: 1,
      });
      console.log(this.cart);
    },
  },
});
// $('#cart').val(JSON.stringify(this.cart));
</script>
      <!--background:
        url('/static/images/map1.jpg');
      background-size: 1500px 805px;
      background-color: #76b5c5;
      font-family: heading; -->
<body style="
      width: 100%;
    height: 100vh;
    background: linear-gradient(rgba(0, 0, 0, 0.2), rgba(0, 0, 0, 0.2)), url('/static/images/bg2.jpg');
    background-size: cover;
    font-family: 'Roboto', sans-serif;
    ">
{% else %}
<p>No items available.</p>
{% endif %} {% endblock %}